name: Build Status

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.x
      uses: actions/setup-node@v1
      with:
        node-version: 22.x
    - run: npm i -f
      env:
        NPM_TOKEN: ${{ secrets.npm_token }}

    - run: npm run test:coverage
